env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: 0,
  indent: [2,2]
}
parser: "babel-eslint"
settings: {
  react: {
    "version": "detect"
  }
}
